services:
  backend:
    build: ./backend
    container_name: shobu-backend
    restart: unless-stopped
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: shobu-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
  postgres:
    image: postgres:17
    container_name: shobu-postgres
    environment:
      POSTGRES_DB: shobu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - shobu-postgres-data:/var/lib/postgresql/
volumes:
  shobu-postgres-data: