spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/shobu
spring.datasource.username=postgres
spring.datasource.password=password
app.players.isaiah-id=${ISAIAH_PLAYER_ID}
app.players.julia-id=${JULIA_PLAYER_ID}