spring.application.name=backend

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:shobu}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD}

app.players.isaiah-id=${ISAIAH_PLAYER_ID}
app.players.julia-id=${JULIA_PLAYER_ID}