on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: shobu
          POSTGRES_USER: shobu
          POSTGRES_PASSWORD: test-password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U shobu -d shobu"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/shobu
        SPRING_DATASOURCE_USERNAME: shobu
        SPRING_DATASOURCE_PASSWORD: test-password


    steps:
      - uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Test backend
        run: ./mvnw test

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v5

      - name: Set Up Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend deps
        run: npm ci

      - name: install front end deps
        run: npm ci

      #      - name: Lint frontend
      #        run: npm run lint

      - name: Build frontend
        run: npm run build

  docker:
    runs-on: ubuntu-latest
    needs: [ backend, frontend ]

    steps:
      - uses: actions/checkout@v5

      - name: build Docker images
        run: docker compose build

  deploy:
    runs-on: ubuntu-latest
    needs: [ backend, frontend, docker ]
    if: github.ref ==  'refs/heads/main'


    steps:
      - name: Deploy To Vps
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/ubuntu/srv/apps/Shobu
            git pull origin main
            docker compose up --build -d
            docker image prune -f 


